### ISSUE TITLE
Unbound: template workaround for broken DHCP

### ISSUE THREAD

**Issue by dgoerger** [dgoerger/workstation#29]
After introducing Unbound for automatic DNSSEC validation, it became apparent that some deployments have very, very broken DHCP, and violate DNSSEC with use of invalid internal-only TLDs (the TLD is ficticious, hence validation fails at the global root).

We should provide a generic template to help admins work around such environments.

e.g. `/etc/unbound/conf.d/workstation.conf`
```
server:
  domain-insecure: {INVALID_ZONE}

forward-zone:
  name: {INVALID_ZONE}
  forward-addr: {INVALID_ZONE_DNS_SERVER}
```
